### ISSUE TITLE
ss_list_sheets only pulling 100 sheets

### ISSUE THREAD

**Issue by sgwhitley** [cole-johanson/smartsheetr#8]
I noticed that ss_list_sheets() only pulls the first 100 sheets(sorted alpha by sheet name) and that these 100 sheets are the only ones available to me for reading by ss_read_sheet. I think that this is related to behavior of the Smartsheet API, which only returns the first 100 sheets unless includeAll = TRUE is included as a parameter. 

Is there a way to include this parameter in the calls being made by functions like ss_list_sheets() and ss_read()?

**Comment by cole-johanson** [comment]
@sgwhitley thanks for bringing this up! This is because pageSize defaults to 100 in the [list sheets API method](https://smartsheet.redoc.ly/tag/sheets#operation/list-sheets).

There are actually a few issues with pagination in the code, so I fixed them all with https://github.com/cole-johanson/smartsheetr/pull/10. 

If you want to use this fix immediately, please run `install_github("cole-johanson/smartsheetr", ref="bug-list-all-sheets")`. 

I will prioritize this for the next release.

**Comment by sgwhitley** [comment]
Thanks! I'll try the dev version after the New Year.
